tc_front:
    resource: "@TCFrontBundle/Controller/"
    type:     annotation
    prefix:   /

tc_tennis:
    resource: "@TCTennisBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    

