tc_front:
    resource: "@TCFrontBundle/Controller/"
    type:     annotation
    host:     "http://tc.dev.distant/RestSymf/web/app_dev.php/"
    prefix:   /

tc_tennis:
    resource: "@TCTennisBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    

