<?php

namespace TC\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarousselPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarousselPageRepository extends EntityRepository
{
}
