<?php

namespace TC\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WelcomeCarouselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WelcomeCarouselRepository extends EntityRepository
{
}
