<?php

namespace TC\TennisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsStreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsStreamRepository extends EntityRepository
{
}
